##############################################
########## Custom Application Value ##########
##############################################
api:
  version: /api/v1
##############################################
########## Server Application Value ##########
##############################################
server:
  port: 8080
##############################################
############## Eureka Client #################
##############################################
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8088/eureka
##############################################
############# Spring properties ##############
##############################################
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: resources
          uri: lb://RESOURCE
          predicates:
            - Path=/api/v1/resources/**
        - id: resourceMetadataModule
          uri: lb://RESOURCE-METADATA
          predicates:
            - Path=/api/v1/resources-metadata/**